.TH WIREDOLPHIN "1" "january 2015" "wiredolphin 1.0.0" "wiredolphin manual"
.SH NAME
wiredolphin - Nicer than sharks.

.SH SYNOPSIS
.B wiredolphin
\fB[\fR\fIOPTIONS...\fR\fB]\fR

.SH DESCRIPTION
Monitor interfaces or offline capture files.

.SH OPTIONS
.SS -f, --filter \R<\fIfilter\fR>
Monitor using the filter <\fIfilter\fR>.

.SS -h, --help
Print a very helpful text.

.SS -i, --interface \fR<\fIinterface_name\fR>
Monitor the interface <\fIinterface_name\fR>.

.SS -o, --offline \fR<\fIfile\fR>
Monitor the offline capture file <\fIfile\fR>.

.SS -o, --verbose \fR<\fIlevel\fR>
Set the verbose mode level:

    \fB0\fR: Raw
    \fB1\fR: Concise
    \fB2\fR: Synthetic
    \fB3\fR: Complete

.SH AUTHOR
    \fBRAZANAJATO RANAIVOARIVONY Harenome\fR <\fIrazanajato@etu.unistra.fr\fR>
    https://github.com/harenome/wiredolphin

.SH LICENSE
This program is free software. It comes without any warranty, to
the extent permitted by applicable law. You can redistribute it
and/or modify it under the terms of the Do What The Fuck You Want
To Public License, Version 2, as published by Sam Hocevar. See
http://www.wtfpl.net/ for more details.
